dataset:
  name: fleurons
  img_size: 256
model:
  name: dtikmeans
  n_prototypes: 36
  encoder_name: resnet20
  transformation_sequence: identity_color_affine
  curriculum_learning: [600, 800]
  gaussian_weights: True
  gaussian_weights_std: 25
training:
  batch_size: 8
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [1200]
    update_range: epoch
  n_epoches: 1500
  train_stat_interval: 100
  val_stat_interval: 100
  check_cluster_interval: 50
  seed: 7832
  visualizer_port:
